env:
  global:
  - REPO_TAG_NAME=$TRAVIS_TAG

os:
  - linux
  - osx

branches:
  only:
    - master
    - /^v.*$/

language: java
install: true
jdk: openjdk12

script:
  - if [ $TRAVIS_TAG == $TRAVIS_BRANCH ]; then export IS_TAG=true; else export IS_TAG=false; fi
  - chmod +x gradlew
  - ./gradlew packageDistribution

deploy:
  tag_name: $TRAVIS_TAG
  provider: releases
  api_key:
    secure: Av567sqYBUvpTumbpfVnKvs20XauwCmJzqDfenDGpjqq0G7JNhE4l1hPdZ8LmsTMZrm0fI09YwqFTFxHphj3oi8S6wv0tv7+n8ByVDLOzyyTnw6Pw9JYOLwjW8RNB9fY7WWHkG1vJkLuQakukMmO1jSBN8hbSb77CF8dEKcNB9OSSsjEfVQn9+b6mtTVJXHmq1q1kc+a/gbkFDFnTGUot8op3N+5XxXcDIc3EqiJ6JAicMPV94aSCuw7qgmrqF3ols0X402xs+OPWEPEB8PDBZ15DZxxKxfgD0AvuC2jnX+ijmd1yxctE4ziWDoT4xmRM3qE+R2JN3aY6RPaK/8hnEHIXe25DipqCVGS5P8btRQ0CK7x48LJolp8HLNPY390GL1BQ2VGSVA0LQwkSlp+LuQovvHxEcubhcw+We2Go0XWPOPp5Ce1CT8yQbFfQPsGjCiWoAC8Uueq3vsxs0dQPpjl+v5MHuIA74VEwzkZeZZYm9phJYqB4MAG0R3aDYy0xTJt6vmPVjKCcQO56kZWL29cBH9z4YcP7eo9FpZuQjMioawDXEU831FvrEAveXZFeYQ5Ufbr9DuhHzfhRF2w22fqPX0SjWBV2WuiPQdTX73qWZwG+pfcaBYkqF3dSfnvKaEiM4qe+glo9TSMuGmP+4huAmAdgUBe+h9w3I5RRLo=
  file_glob: true
  file:
    - build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true



