trigger:
  branches:
    include:
      - master
      - '*-dev'
  tags:
    include:
      - v*

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  system.debug: false
  isTag: 'false'
  isSnapshot: 'false'

jobs:
  # Linux app bundle job
  - template: build-job.yml
    parameters:
      name: app_bundle_linux
      platform: linux
      jdkDownloadUrl: 'https://cdn.azul.com/zulu/bin/zulu13.28.11-ca-jdk13.0.1-linux_x64.tar.gz'
      jdkFile:  $(Agent.TempDirectory)/jdk-latest-linux_x64.tar.gz
      pool:
        vmImage: 'ubuntu-16.04'

  # MacOS app bundle job
  - template: build-job.yml
    parameters:
      name: app_bundle_mac
      platform: mac
      jdkDownloadUrl: 'https://cdn.azul.com/zulu/bin/zulu13.28.11-ca-jdk13.0.1-macosx_x64.tar.gz'
      jdkFile: $(Agent.TempDirectory)/jdk-latest-macosx_x64.tar.gz
      pool:
        vmImage: 'macOS-10.14'

  # Windows app bundle job
  - template: build-job.yml
    parameters:
      name: app_bundle_windows
      platform: win
      jdkDownloadUrl: 'https://cdn.azul.com/zulu/bin/zulu13.28.11-ca-jdk13.0.1-win_x64.zip'
      jdkFile: $(Agent.TempDirectory)/jdk-latest-win_x64.zip
      pool:
        vmImage: 'windows-2019'

